prometheus_scrape_configs:
  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'srv1.poc.lan:9100'
        - 'srv2.poc.lan:9100'
        - 'srv3.poc.lan:9100'
        - 'srv4.poc.lan:9100'
        - 'srv5.poc.lan:9100'

grafana_security:
  admin_user: admin
  admin_password: admin

prometheus_web_listen_address: "0.0.0.0:9090"
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://{{ prometheus_web_listen_address }}'
    basicAuth: false
