name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - "doc/"
  pull_request:
    branches: [ "master" ]
    paths:
      - "doc/"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd doc/
        docker build -t bpimg -f docker/Dockerfile .

    - name: Build the proposal
      run: |
        cd doc/
        docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh voorstel

    - name: Build the thesis
      run: |
        cd doc/
        docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh bachproef

    - name: Build the poster
      run: |
        cd doc/
        docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh poster

    - uses: actions/upload-artifact@v3
      name: Upload artifacts
      with:
        name: output
        path: |
          output/*.pdf
          output/*.log
        if-no-files-found: error
