---
name: Build proposal
on:
  push:
    branches:
      - master
    paths:
      - doc/voorstel/**
  pull_request:
    branches:
      - master
    paths:
      - doc/voorstel/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          cd doc/
          docker build -t bpimg -f docker/Dockerfile .
      - name: Build the proposal
        run: >
          cd doc/

          docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh voorstel
      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: output
          path: |
            doc/output/*.pdf
            doc/output/*.log
          if-no-files-found: error
